### ISSUE TITLE
LSTM makes error with test data set

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/PV-forecasting#1]

**Comment by daisukekodaira** [comment]
#Issue
The prediction result is all 0

#What is the cause?
Maybe dataset.
The model is trained with smaller LongTermPastData.csv.

#What we should do?
Make it works with smaller LongTermPastData.




![ANN](https://user-images.githubusercontent.com/43132698/58256032-35f98200-7da9-11e9-91d0-bfebe67cff56.jpeg)
![combined](https://user-images.githubusercontent.com/43132698/58256033-35f98200-7da9-11e9-895a-0ffdf93da6d0.jpeg)
![LSTM](https://user-images.githubusercontent.com/43132698/58256034-36921880-7da9-11e9-8b27-fee9206c6a0d.jpeg)

**Comment by gyeonggak** [comment]
![LSTM](https://user-images.githubusercontent.com/50954796/58395264-4730e000-8082-11e9-925f-9b6c0120c24c.PNG)

i modified code and made result
