### ISSUE TITLE
Error on "PVset_PV_kmeans" with KIAPI data set

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/PV-forecasting#2]
**Describe the bug**
PVset_PV_kmeans shows the following error with dataset "PLT_201905191020.csv".

**To Reproduce**
Run PVset_main.m with PLT_201905191020.csv

**Expected behavior**
No error

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43132698/58535177-3c17b480-8228-11e9-8b0d-ec07a97a1c43.JPG)

**Matlab version:**
2019a

**Additional context(in Korean also ok)**

**Comment by gyeonggak** [comment]
I modified
