### ISSUE TITLE
Error correction make forecasting results worse

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/PV-forecasting#6]
- **Describe the bug**
In "PVset_kmeans_Forecast", error correction make forecasting results worse.

- **Current implementation**
we just let do error_correction, but the result of error_correction is not adopted 
for the final forecasting result because it makes the result worse.

- **Expected behavior**
1. We need to check if the error correction is implemented as we expect. (but I don't know what we originally expect....)
2. We need to find out the error correction really can improve the forecasting accuracy.
3. If the error correction doesn't contribute, just remove all error correction parts.
    otherwise, we need to prof the result is improved by the error correction

- **Screenshots**
![Capture](https://user-images.githubusercontent.com/43132698/69492933-c4cb9080-0eeb-11ea-9daa-d8bef00fcf82.JPG)

- **matlab version:**
R2019a

**Comment by kazukitukazaki** [comment]
解決しました。
