### ISSUE TITLE
Chose the best k by gap statistics

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/PV-forecasting#7]
- **Is your feature request related to a problem? Please describe.**
Calculation time of "PVset_kmeans_Forecast" require much calculation time and performance is still not good. The current implementation is as follows:

`for k = 1 to 10     # investigate from k =1 to 10 `
`___for attempt = 1 to 3`
`______try "k" and check the forecasting result `
`___end `
`___calculate the average of 3 attempts`
`end`

![Capture](https://user-images.githubusercontent.com/43132698/69492956-0825ff00-0eec-11ea-966a-5ce74cb6014b.JPG)

- **Describe the solution you'd like**
Introduce gap statistics function to decide the optimal k.
You can find gap statistics function here;
[evalclusters](https://www.mathworks.com/help/stats/clustering.evaluation.gapevaluation-class.html)

- **Matlab version**
R2019a

**Comment by kazukitukazaki** [comment]
解決しました。
